# Generated by Django 5.1.7 on 2025-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_tripsegmentstep_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripleg',
            name='end_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='end_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='start_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
