# Generated by Django 5.1.7 on 2025-04-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripleg',
            name='polyline_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
