# Generated by Django 5.1.7 on 2025-04-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tripleg_polyline_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripleg',
            name='end_label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='start_label',
            field=models.TextField(),
        ),
    ]
