# Generated by Django 5.1.8 on 2025-04-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_tripleg_end_label_alter_tripleg_start_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripleg',
            options={'ordering': ['leg_order']},
        ),
        migrations.AlterModelOptions(
            name='tripsegmentstep',
            options={'ordering': ['step_order']},
        ),
    ]
